# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit r_journal.Rmd to modify this file

## ---- include=F---------------------------------------------------------------
knitr::opts_chunk$set(message = F, 
                      warning = F, 
                      comment = "    ", 
                      out.width = "69%")
kabel_format <- "latex"


library(magrittr)
readLines("../../../README.Rmd")  %>%  .[44:length(.)] %>% 
  writeLines("../../../readme_extract.Rmd")


## ---- child = "../../../readme_extract.Rmd"-----------------------------------

## ----manipulation_status_quo--------------------------------------------------
library(tidyverse)
tidytitanic::passengers %>% 
  tibble() %>% 
  mutate(cat_survived = ifelse(survived, 
                               "survived", 
                               "not survived"), 
         .before = 1)


## ----visual_status_quo--------------------------------------------------------
tidytitanic::passengers %>% 
ggplot() + 
  aes(x = sex) + 
  geom_bar() + 
  facet_grid(~ ifelse(survived, 
                      "survived", 
                      "not survived")) 


## ----visual_status_quo_order--------------------------------------------------
data.frame(ind_daytime = c(T, F, T, T)) %>% 
    mutate(cat_survived = ifelse(ind_daytime, "daytime", "not daytime")) %>% 
  mutate(cat_survived = fct_rev(cat_survived)) %>% 
  ggplot() + 
  aes(x = cat_survived) + 
  geom_bar()


## ----direct_table_awkward-----------------------------------------------------
tidytitanic::passengers %>% 
  count(survived) 


## ----direct_table_loss--------------------------------------------------------
tidytitanic::passengers %>% 
  janitor::tabyl(sex, survived)


## ----direct_visual_awkward, fig.cap="A. Bar labels + axis label preserves information but is awkward"----
library(tidyverse)

tidytitanic::passengers %>% 
  ggplot() + 
  aes(x = survived) + 
  geom_bar()


## ----direct_visual_loss, fig.cap = "D. Facetting directly on an indicator variable with popular ggplot2 results in information loss"----
tidytitanic::passengers %>% 
ggplot() + 
  aes(x = age) + 
  geom_histogram() + 
  facet_grid(~ survived)


## ----manipulation_status_quo_reprise, eval = T, message=F, warning=F----------
library(tidyverse)

data.frame(ind_graduated = 
             c(TRUE, TRUE, FALSE))  %>% 
  mutate(cat_graduated  = 
           ifelse(ind_graduated, 
                  "graduated", 
                  "not graduated"))  %>% 
  mutate(cat_graduated = 
           fct_rev(cat_graduated)
         )  


## ----manipulation_ind2cat, eval = T, message=F, warning=F---------------------
library(ind2cat)

data.frame(ind_graduated = 
             c(TRUE, TRUE, FALSE)) %>% 
  mutate(cat_graduated  = 
           ind_recode(ind_graduated)
         )


## ----manipulation_ind2cat_custom----------------------------------------------
data.frame(ind_graduated = c(T,T,F)) %>% 
  mutate(cat_graduated  = ind_recode(ind_graduated, 
                                     cat_false = "current"))


## ----manipulation_custom_cat_true---------------------------------------------

tibble(ind_grad = c("y", "n")) %>%
  mutate(cat_grad  = ind_recode(ind_grad, 
                                cat_true = "graduated"))


## ----manipulation_custom_negator----------------------------------------------

tibble(ind_grad = c(T,T,F)) %>%
  mutate(cat_grad  = ind_recode(ind_grad, negator = "didn't"))


## ----manipulation_custom_false_cat--------------------------------------------
tibble(ind_grad = c("Y", "N")) %>%
  mutate(cat_grad  = ind_recode(ind_grad, cat_false = "enrolled"))


## ----manipulation_custom_rev--------------------------------------------------
tibble(ind_grad = c("yes", "no")) %>%
  mutate(cat_grad  = ind_recode(ind_grad, rev = TRUE)) %>% 
  mutate(cat_grad_num = as.numeric(cat_grad))


## ----manipulation_custom_prefix-----------------------------------------------
tibble(dummy_grad = c(0,0,1,1,1 ,0 ,0)) %>%
  mutate(cat_grad  = ind_recode(dummy_grad, var_prefix = "dummy_"))



## ----visual_ind2cat_improves--------------------------------------------------
tidytitanic::passengers %>% 
ggplot() + 
  aes(x = ind_recode(survived)) + 
  geom_bar()


## ----visual_ind2cat_improves_cat_false----------------------------------------
# or
last_plot() +
  aes(x = ind_recode(survived, cat_false = "perished"))


## ----visual_ind2cat_improves_cat_false_rev------------------------------------
# or
last_plot() +
  aes(x = ind_recode(survived, cat_false = "didn't", rev = T)) + 
  labs(x = NULL)



## ----visual_ind2cat_preserves-------------------------------------------------

tidytitanic::passengers %>% 
ggplot() + 
  aes(x = sex) + 
  geom_bar() + 
  facet_grid(~ ind_recode(survived))


## ----table_ind2cat_preserves--------------------------------------------------
tidytitanic::passengers %>%
  mutate(cat_survived = ind_recode(survived)) %>% 
  janitor::tabyl(sex, cat_survived) %>% 
  janitor::adorn_percentages() %>% 
  janitor::adorn_pct_formatting() %>% 
  janitor::adorn_ns(position = "rear")


## -----------------------------------------------------------------------------
readLines("R/ind_recode.R") -> implementation


## ---- code = implementation, eval= F------------------------------------------
#> NA


